### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by hermankamooni** [Social-Systems-Lab/circles#18]
We need a server (Sort of like DNS) that can route members to circles

**Comment by patrik-u** [comment]
Foundation done. Future work that remains are among other things: 

- verify user email and handle is globally unique when signing up
- changes in log in and sign up process to allow users to log in to different instances without creating new account (e.g. by them specifying email before moving on to next step).
- synching of user data between instances, specially when logging in to a new instance for the first time
