### ISSUE TITLE
Dev setup

### ISSUE THREAD

**Issue by hermankamooni** [Social-Systems-Lab/circles#4]
- [ ] Installing requirements [preferably a executable or script requirements.txt with list of libraries and versions]
- [ ] env recommendation
- [ ] MongoDb setup [to cloud test server as before] ?
- [ ] deploying with docker in dev also?
- [ ] final ReadMe with steps

**Comment by patrik-u** [comment]
Local dev setup docs: https://github.com/Social-Systems-Lab/circles/blob/dev/docs/dev-onboarding.md
Deployment docs (Raspberry Pi): https://github.com/Social-Systems-Lab/circles/blob/dev/docs/server-setup.md

Answers: 
Installing requirements - For production environment. You need docker and docker compose, see deployment docs.
env recommendation - See deployment docs.
"MongoDB setup [to cloud test server as before]?" - DB is deployed/run through docker, and it's run locally on dev, and deployed on test server
"Deploying with docker in dev also?" - partially (db, storage and reverse proxy runs in docker), see the Local dev setup docs. 
"final ReadMe with steps" - See deployment docs
